### ISSUE TITLE
Health = Problem

### ISSUE THREAD

**Issue by MadsBen** [jnxxx/homeassistant-connectedcars_io#11]
Hi

I'm using the integration for my Skoda Octavia. A couple of weeks ago, the "Health" entitlement started to report "problem". I got no warning lights or issues reported by the car or the "MinSkoda" app.
I have enabled debug logging for this and can see this in the "Got vehicle data" call:
`"health": {"ok": false, "recommendation": null}`

**Comment by jnxxx** [comment]
What is the service status?
I believe mine lit up last time it was up for service.

**Comment by MadsBen** [comment]
> What is the service status?
> I believe mine lit up last time it was up for service.

It had service about 4 weeks ago, as I recall it was before the "service" warning appeared in the car. Could be that the service timer has not been reset in the backend. In the MinSkoda app, the countdown till next service is correct.

I will try to fiddle around with the API or maybe contact connectedcars.io.

**Comment by Kjagd** [comment]
Hi, in general you should rely on `leads` now. 
For example for service you could pull something like this: 
```
  vehicle {
    leads(types: [service_reminder]) {
      id
      status
      dismissed
      context {
        ... on LeadServiceReminderContext {
          serviceDate
          sourceData {
            type
            value
          }
        }
      }
    }
  }   
  ```
  
Note that pulling leads directly on vehicle will give you a list of all the different leads, and not just the health trigger. (I would recommend this, since health essentially is priority-list of leads, but it's probably more useful to fetch all). See LeadType enum for a list of all the different types, though I don't believe _all_ of them are currently in use. Feel free to ask away.
    
Best regards Kristian from Connected Cars

**Comment by jnxxx** [comment]
Thank you @Kjagd.
This is very helpful.

Can I assume there is a relation between these `leads` and `health { ok }` status?
Meaning if not ok, is there one or more open leads explaining the cause.
And vice versa, if ok, then there are no open leads.
Or can there be open leads while ok is true?

**Comment by jnxxx** [comment]
@MadsBen, if you still have the health issue indicated, please try the pre-release v1.1.0.
(redownload if you already had the pre-release)

On the `Health` sensor, you should now get an additional attribute named `Leads`.
This will be an array of leads where the state is open.
Ideally it should be empty, but if an issue is indicated there may be one or more.

I did not have any currently open leads, but for testing purposes I made it temporarily list the historic ones.
These are some examples of leads it can show:
```
Leads:
  - type: error_code
    createdTime: '2023-07-30T14:54:33.000Z'
    updatedTime: '2023-08-24T18:09:26.000Z'
    severityScore: 10
    context:
      errorCode: U113800
      ecu: central_electrics
      provider: VAG
      errorCodeCount: 16
      description: Sensor for Anti-Theft Alarm System - Implausible Message
  - type: service_reminder
    createdTime: '2023-04-09T00:02:51.000Z'
    updatedTime: '2023-04-27T12:20:43.000Z'
    bookingTime: '2023-05-11T00:00:00.000Z'
    lastContactedTime: '2023-04-25T07:00:09.000Z'
    severityScore: 10
    value: 5000 DKK
    context:
      serviceDate: '2023-05-09T00:00:00.000Z'
      oilEstimateUncertain: false
      interval_service_days: '2023-05-09T00:00:00.000Z'
  - type: poor_battery
    createdTime: '2022-07-22T02:15:15.000Z'
    updatedTime: '2022-07-23T10:05:25.000Z'
    severityScore: 10
    value: 1500 DKK
    context:
      sourceMedianVoltage:
        voltage: 11.947
```

But as @Kjagd wrote, there are even more types than this, although some might not be used currently.

**Comment by MadsBen** [comment]
@jnxxx Thanks for the update. I got some leads in there, like this one that might be the culprit. 

The next question is then whether this is a "real" warning or a bug. I do not get any warning lights for this in the car or the MinSkoda app. But that's unrelated for this integration.

```
description: Databus - Received Error Message
- type: error_code
  createdTime: '2023-06-20T05:12:12.000Z'
  updatedTime: '2023-09-01T04:43:22.000Z'
  severityScore: 10
  context:
    errorCode: P20EE00
    ecu: engine
    provider: VAG
    errorCodeCount: 193
    description: NOx Catalyst Efficiency Below Threshold Bank 1
```
